# Generated by Django 3.1.1 on 2020-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_auto_20200910_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(default='Nothing!', max_length=300, verbose_name='ToDos'),
        ),
    ]
